Added updated provisioning template graphic
esper-io/dev-docs pull request #226
Opened 2020-09-23 16:02 UTC by celanthe

Added updated provisioning template graphic for DevRel 44

2020-09-23 22:27 UTC, QueenOvDroids approved these changes

2020-09-24 15:30 UTC, kirananto requested changes

2020-09-24 15:30 UTC, kirananto commented on docs/home/console.md
> +***Tip: The Simulare feature is only available on accounts created after Friday, September 27, 2019. If you became an Esper client before then and would like access to a simulated device, please [con
@celanthe You could use the :::tip Feature of vuepress...

Just that the ending tag has to be in new line.. 
For more info: https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers

:::tip
The Simulare feature is only available on accounts created after Friday, September 27, 2019. If you became an Esper client before then and would like access to a simulated device, please [contact us](mailto:support@esper.io).
:::

2020-09-24 15:30 UTC, kirananto commented on docs/home/console.md
> +***Tip: Please note that disabling USB tethering also disables Wi-Fi tethering.***
Same case here. ^^ 

Ignore this comment if it's intentional

2020-09-24 15:30 UTC, kirananto commented on docs/home/console.md
> +***Tip: Before using a managed Google Play account, you need to set up a Managed Google Play account through Esper.***
Same here... ^^

2020-09-24 17:36 UTC, celanthe commented on docs/home/console.md
> +***Tip: Please note that disabling USB tethering also disables Wi-Fi tethering.***
This is intentional, yes! :) Cheers!

2020-09-24 17:36 UTC, celanthe commented on docs/home/console.md
> +***Tip: The Simulare feature is only available on accounts created after Friday, September 27, 2019. If you became an Esper client before then and would like access to a simulated device, please [con
This was an intentional change! :) Cheers!

2020-09-25 14:54 UTC, kirananto commented on docs/home/console.md
> +![Groups](.assets/NewConsole/movegroupsupdated.png)
It is not
.assets/NewConsole/movegroupsupdated.png

It is
./assets/NewConsole/movegroupsupdated.png

2020-09-29 03:17 UTC, kirananto commented
Looks good to be merged... Merging...

2020-09-29 03:17 UTC, merged