Updated device SDK documentation
esper-io/dev-docs pull request #281
Opened 2020-11-19 21:30 UTC by celanthe

Updated device SDK documentation with information on  two new SDK APIs we introduced in this sprint: APN config & disable power off via Samsung Knox.

2020-11-19 21:33 UTC, celanthe commented on docs/home/devicesdk.md
>  EsperDeviceSDK sdk = EsperDeviceSDK.getInstance(getApplicationContext());
@ankitgupta29 @mihirEsper Hi! What is the updated information needed in the implementation files dependencies section to bring lines 27-28 up to date with the Tessarion_MR8 2.0.6 release?

Thank you so much.

2020-11-20 16:29 UTC, mihirEsper requested changes

2020-11-20 16:29 UTC, mihirEsper commented on docs/home/devicesdk.md
>  EsperDeviceSDK sdk = EsperDeviceSDK.getInstance(getApplicationContext());
replace `esperdevicesdk-release-v1.2.4` with `app-2.0.6225.9`

2020-11-20 16:29 UTC, mihirEsper commented on docs/home/devicesdk.md
> +sdk.allowPowerOff(checked, new EsperDeviceSDK.Callback<Boolean>() {
replace checked with `true/false`.

2020-11-20 16:29 UTC, mihirEsper commented on docs/home/devicesdk.md
> +These APIs are only available on Samsung KNOX enabled devices, via Supervisor plugin, and the Esper Device SDK version TESSARION_MR8.
Samsung KNOX enabled devices OR via Supervisor plugin

2020-11-20 16:29 UTC, mihirEsper commented on docs/home/devicesdk.md
> +```java
shouldn't it be JSON?

2020-11-20 16:29 UTC, mihirEsper commented on docs/home/devicesdk.md
> +removeApnConfig expects APN ID in argument returned by addNewApnConfig function.
repalce `removeApnConfig ` with `setDefaultApn`

2020-11-20 17:19 UTC, celanthe commented on docs/home/devicesdk.md
> +removeApnConfig expects APN ID in argument returned by addNewApnConfig function.
Done, will be pushing the commit with this change shortly.

2020-11-20 17:20 UTC, celanthe commented on docs/home/devicesdk.md
> +```java
I've changed all instances to be JSON instead of Java, thanks for the tip!

2020-11-20 17:20 UTC, celanthe commented on docs/home/devicesdk.md
> +These APIs are only available on Samsung KNOX enabled devices, via Supervisor plugin, and the Esper Device SDK version TESSARION_MR8.
Made this change, thank you!

2020-11-20 17:20 UTC, celanthe commented on docs/home/devicesdk.md
> +sdk.allowPowerOff(checked, new EsperDeviceSDK.Callback<Boolean>() {
Change made!

2020-11-20 17:21 UTC, celanthe commented on docs/home/devicesdk.md
>  EsperDeviceSDK sdk = EsperDeviceSDK.getInstance(getApplicationContext());
Thank you so much!

2020-11-21 13:00 UTC, mihirEsper requested changes
JSON had to be used only from line# 396-419. rest of of the places `java` correct & does not require a change

2020-11-23 16:31 UTC, celanthe commented
> JSON had to be used only from line# 396-419. rest of of the places `java` correct & does not require a change

Hi @mihirEsper thanks for letting me know the exact lines to have that change apply to. I've updated the rest of the instances back to Java!

2020-11-23 16:38 UTC, mihirEsper approved these changes
lgtm!

2020-11-24 16:30 UTC, merged