Added a EQL hidden page
esper-io/dev-docs pull request #349
Opened 2021-12-08 05:56 UTC by radhak21

2021-12-08 09:03 UTC, pallavigopi commented
@radhak21 @tarun91vas which URL can this page be accessed from?

2021-12-08 09:10 UTC, tarun91vas requested changes

2021-12-08 09:10 UTC, tarun91vas commented on docs/home/eql/README.md
> +3.  Queries): These are the types of EQL queries.
additional closing brace

2021-12-08 09:10 UTC, tarun91vas commented on docs/home/eql/README.md
> +details.url:"https://esper.io"
This will not come in the code block. we should include single code blocks like this `details.url:"https://esper.io"`

This needs to be done for all the statements which were present in code blocks in the original documentation. You can refer to markdown documentation for the same.

2021-12-08 09:10 UTC, tarun91vas commented on docs/home/eql/README.md
> +```
please format both this JSON using an online tool. Formatting is not correct here, everything is moved to left side.

2021-12-08 09:10 UTC, tarun91vas commented on docs/home/eql/README.md
> +{
Format this JSON as well.

2021-12-09 09:10 UTC, tarun91vas commented
@pallavigopi did not get your question which url as in ?

2021-12-09 09:11 UTC, tarun91vas approved these changes

2021-12-09 09:17 UTC, merged